name: Build Nuitka EXE for Windows and Linux AppImage
on:
  push:
    branches:
      - main
  release:
    types: [created]
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Verify file path
        run: |
          Get-ChildItem -Recurse
          if (Test-Path -Path "src\Stegatool-v0-1-1.py") {
              Write-Output "File exists"
          } else {
              Write-Output "File does not exist"
              exit 1
          }
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install nuitka
          pip install pyqt6 pillow numpy opencv-python scipy reedsolo pydub pycryptodome
      - name: Download dependency walker manually
        shell: powershell
        run: |
          $dependsUrl = "https://dependencywalker.com/depends22_x64.zip"
          $downloadPath = "depends22_x64.zip"
          $extractPath = "C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache\downloads\depends\x86_64"
          
          # Create directories if they don't exist
          New-Item -Path $extractPath -ItemType Directory -Force
          
          # Download the file
          Invoke-WebRequest -Uri $dependsUrl -OutFile $downloadPath
          
          # Extract the archive
          Expand-Archive -Path $downloadPath -DestinationPath $extractPath -Force
          
          # Verify files were extracted
          Get-ChildItem -Path $extractPath
      - name: Build with Nuitka
        shell: cmd
        run: |
          cd src
          python -m nuitka Stegatool-v0-1-1.py --standalone --lto=yes --onefile --follow-imports --enable-plugin=pyqt6 --output-dir=..\build --windows-console-mode=disable --assume-yes-for-downloads
      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stegatool-Windows
          path: build/Stegatool-v0-1-1.exe
      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: build/Stegatool-v0-1-1.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Verify file path
        run: |
          find .
          if [ -f "src/Stegatool-v0-1-1.py" ]; then
              echo "File exists"
          else
              echo "File does not exist"
              exit 1
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf desktop-file-utils libgirepository1.0-dev libfuse2 imagemagick
          pip install nuitka
          pip install pyqt6 pillow numpy opencv-python scipy reedsolo pydub pycryptodome
      - name: Build with Nuitka
        run: |
          cd src
          python -m nuitka Stegatool-v0-1-1.py --standalone --onefile --enable-plugin=pyqt6 --output-dir=../build --lto=yes --follow-imports --assume-yes-for-downloads
      - name: Verify build output
        run: |
          ls -la build/
      - name: Download and extract appimagetool
        run: |
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ./appimagetool-x86_64.AppImage --appimage-extract
      - name: Create AppDir structure
        run: |
          # Create basic structure
          mkdir -p AppDir/usr/bin
          cp build/Stegatool-v0-1-1.bin AppDir/usr/bin/stegatool
          chmod +x AppDir/usr/bin/stegatool
          
          # Create AppRun script
          cat > AppDir/AppRun << 'EOF'
          #!/bin/bash
          HERE="$(dirname "$(readlink -f "${0}")")"
          exec "$HERE/usr/bin/stegatool" "$@"
          EOF
          chmod +x AppDir/AppRun
          
          # Create desktop entry in root directory
          cat > AppDir/stegatool.desktop << EOF
          [Desktop Entry]
          Name=Stegatool
          Exec=stegatool
          Icon=stegatool
          Type=Application
          Categories=Utility;
          EOF
          
          # Create icon directly in root directory
          convert -size 256x256 xc:white -fill black -pointsize 24 -gravity center -annotate 0 "Stegatool" AppDir/stegatool.png
          
          # Debug: List the AppDir structure to verify
          find AppDir -type f | sort
      - name: Create AppImage using extracted appimagetool
        run: |
          ./squashfs-root/AppRun AppDir Stegatool-v0-1-1-x86_64.AppImage
      - name: Upload AppImage as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stegatool-Linux
          path: Stegatool-v0-1-1-x86_64.AppImage
      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: Stegatool-v0-1-1-x86_64.AppImage
